nvenkateswarlu90/A4DataPro

- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/criteria/parser/CatalogParser.java
completed with catalog and image.
> catalog and image completed

- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/CatalogParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/PersonlizationParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/PriceGridParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductArtworkProcessor.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductColorParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductImprintColorParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductImprintMethodParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductImprintSizeLocParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductMaterialParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductNumberParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductOptionParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductOriginParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductPackagingParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductPersonlizationParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductRushTimeParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductSameDayParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductSampleParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductShapeParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductSizeParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductSkuParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductThemeParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductTradeNameParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductionTimeParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ShippingEstimationParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/usbProducts/excelMapping/UsbProductsExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/criteria/parser/ProductImprintColorParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/ApplicationConstants.java
Completed dev for 2nd section of Supplier fields.
> Completed dev for 2nd section of Supplier fields.

- A4techExcelConvertionTool/src/main/java/com/a4tech/v2/core/excelMapping/ExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/v2/criteria/parser/ProductImprintColorParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/v2/criteria/parser/ProductImprintMethodParser.java
> 2nd part v2 completed

- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/usbProducts/excelMapping/UsbProductsExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/service/postImpl/PostServiceImpl.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
> commit with rest template

- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/mapping/SageProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/parser/ColorParser.java
- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/parser/DimensionParser.java
- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/util/LookupData.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/criteria/parser/ProductColorParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/model/ProductConfigurations.java
> partial commit with sage Excel

- A4techExcelConvertionTool/main/java/supplier/JulyData/com/a4tech/JulyData/excelMapping/JulyDataMapping.java
- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/mapping/SageProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/usbProducts/excelMapping/UsbProductsExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/errors/DownloadServlet.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/dao/service/ProductDao.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/service/PostService.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/service/ProductService.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/service/imple/ProductServiceImpl.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/service/postImpl/PostServiceImpl.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/v2/core/excelMapping/ExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/v2/service/postImpl/PostServiceImpl.java
- A4techExcelConvertionTool/src/main/resources/application.properties
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
- A4techExcelConvertionTool/src/main/resources/spring/sageMapping.xml
- A4techExcelConvertionTool/src/main/webapp/WEB-INF/views/success.jsp
- A4techExcelConvertionTool/src/main/webapp/WEB-INF/web.xml
Error Log reporting to Txt File.
> Error Log reporting to Txt File.

- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/mapping/SageProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/parser/DimensionParser.java
- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/util/LookupData.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/ApplicationConstants.java
> size and theme completed

- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/DownloadFileController.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/ApplicationConstants.java
- A4techExcelConvertionTool/src/main/resources/application.properties
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
- A4techExcelConvertionTool/src/main/webapp/WEB-INF/views/success.jsp
> Email Task Done.

- A4techExcelConvertionTool/pom.xml
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/DownloadFileController.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
Done mailing using  JavaMailSender
> Done mailing using  JavaMailSender

- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/mapping/SageProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/parser/PriceGridParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductColorParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductImprintColorParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductImprintMethodParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductImprintSizeLocParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductNumberParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductSizeParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/product/USBProducts/criteria/parser/ProductSkuParser.java
- A4techExcelConvertionTool/main/java/supplier/USBProducts/com/a4tech/usbProducts/excelMapping/UsbProductsExcelMapping.java
removed unused code from project
> removed unused code from project

- A4techExcelConvertionTool/src/main/webapp/WEB-INF/views/home.jsp
> code changes on submit button

- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/dc/product/mapping/DCProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/product/DCProducts/parser/DCPriceGridParser.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
> 	Pricing Completed.

- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/dc/product/mapping/DCProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/product/DCProducts/parser/ProductOriginParser.java
Done Product Level & Other Attributes.
> Done Product Level & Other Attributes

- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/dc/product/mapping/CommonUtility.java
- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/dc/product/mapping/DCProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/product/DCProducts/parser/ProductOriginParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/DownloadFileController.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/ApplicationConstants.java
changes done in application constant class and OR operator
> changes done in application constant class and OR operator

- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/dc/product/mapping/DCProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/product/DCProducts/parser/DCPriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/SupplierMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/criteria/parser/PriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/criteria/parser/ProductRushTimeParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/criteria/parser/UsbProductsPriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/v2/core/excelMapping/V2ExcelMapping.java
Done Error Logging & Exception Handling in few cases .
> Done Error Logging & Exception Handling in few cases .

- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/parser/PriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/DownloadFileController.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/dao/service/ProductDao.java
changes done in price grid parser.
> changes done in price grid parser

- A4techExcelConvertionTool/src/main/java/com/a4tech/product/service/postImpl/PostServiceImpl.java
changes done in postserviceimpl
> changes done in postserviceimpl

- A4techExcelConvertionTool/src/main/webapp/WEB-INF/views/home.jsp
- A4techExcelConvertionTool/src/main/webapp/resources/css/style.css
Done changes in validation messages.
> Done changes in validation messages.

- A4techExcelConvertionTool/src/main/resources/log4j.properties
> changes done in log4J

- A4techExcelConvertionTool/src/main/webapp/WEB-INF/views/home.jsp
- A4techExcelConvertionTool/src/main/webapp/WEB-INF/views/success.jsp
- A4techExcelConvertionTool/src/main/webapp/resources/css/style.css
changes done in design part(Author-Rupesh)
> changes done in design part(Author-Rupesh)

- A4techExcelConvertionTool/.classpath
- A4techExcelConvertionTool/.settings/org.eclipse.wst.common.component
- A4techExcelConvertionTool/main/java/supplier/91561ESPTemplate/com/a4tech/ESPTemplate/product/mapping/ESPTemplateMapping.java
- A4techExcelConvertionTool/main/java/supplier/91561ESPTemplate/com/a4tech/product/ESPTemplate/parser/ColorParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/service/postImpl/PostServiceImpl.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/ApplicationConstants.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
> commit with ESP Template

- A4techExcelConvertionTool/main/java/supplier/91561ESPTemplate/com/a4tech/product/ESPTemplate/parser/OriginParser.java
- A4techExcelConvertionTool/main/java/supplier/91561ESPTemplate/com/a4tech/product/ESPTemplate/parser/PriceGridParser.java
- A4techExcelConvertionTool/main/java/supplier/91561ESPTemplate/com/a4tech/product/ESPTemplate/parser/ProductImprintMethodParser.java
- A4techExcelConvertionTool/main/java/supplier/91561ESPTemplate/com/a4tech/product/ESPTemplate/parser/ProductMaterialParser.java
- A4techExcelConvertionTool/main/java/supplier/91561ESPTemplate/com/a4tech/product/ESPTemplate/parser/RushTimeParser.java
- A4techExcelConvertionTool/main/java/supplier/91561ESPTemplate/com/a4tech/product/ESPTemplate/parser/ShippingEstimationParser.java
- A4techExcelConvertionTool/main/java/supplier/91561ESPTemplate/com/a4tech/product/ESPTemplate/parser/SizeParser.java
> commit with all parser

- A4techExcelConvertionTool/.classpath
- A4techExcelConvertionTool/.settings/org.eclipse.wst.common.component
- A4techExcelConvertionTool/main/java/supplier/40445BBI/com/a4tech/product/bbi/criteria/parser/BBIPriceGridParser.java
- A4techExcelConvertionTool/main/java/supplier/40445BBI/com/a4tech/product/bbi/criteria/parser/ProductImprintMethodParser.java
- A4techExcelConvertionTool/main/java/supplier/40445BBI/com/a4tech/product/bbi/criteria/parser/ProductSizeParser.java
- A4techExcelConvertionTool/main/java/supplier/40445BBI/com/a4tech/product/bbi/mapping/BBIProductsExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/service/postImpl/PostServiceImpl.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/ApplicationConstants.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
40445 (New BBI Term) Completed.
> 40445 (New BBI Term) Completed.

- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/dc/product/mapping/DCProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/product/DCProducts/parser/ProductOriginParser.java
- A4techExcelConvertionTool/main/java/supplier/kuku/com/a4tech/product/kuku/criteria/parser/KukuPriceGridParser.java
- A4techExcelConvertionTool/main/java/supplier/kuku/com/a4tech/product/kuku/mapping/KukuProductsExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
Done with removing special char,words,html tag in DC Supplier.
> Done with removing special char,words,html tag in DC Supplier.

- A4techExcelConvertionTool/main/java/supplier/40445BBI/com/a4tech/product/bbi/mapping/BBIProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/DistributorCentral/com/a4tech/dc/product/mapping/DCProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/kuku/com/a4tech/product/kuku/mapping/KukuProductsExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/CommonUtility.java
Code changes to make use of utility mehtod & replacing hard core values for kuku,bbi,DC supplier.
> 	Code changes to make use of utility mehtod & replacing hard core values.

- A4techExcelConvertionTool/main/java/supplier/82283RFGLine/com/a4tech/RFGLine/products/parser/RFGProductAttributeParser.java
- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/mapping/SageProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/Sage/com/a4tech/sage/product/parser/PriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
> A4 tech excel convert1.0

- A4techExcelConvertionTool/main/java/supplier/82283RFGLine/com/a4tech/RFGLine/products/parser/RFGDescrptionParser.java
- A4techExcelConvertionTool/main/java/supplier/82283RFGLine/com/a4tech/RFGLine/products/parser/RFGPriceGridParser.java
changes done in upcharges and description.
> changes done in upcharges and description.

- A4techExcelConvertionTool/.classpath
- A4techExcelConvertionTool/.settings/org.eclipse.wst.common.component
- A4techExcelConvertionTool/main/java/supplier/64905/com/a4tech/kl/product/mapping/KlProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/91284NewPro/com/a4tech/product/newproducts/criteria/parser/NewProPriceGridParser.java
- A4techExcelConvertionTool/main/java/supplier/91284NewPro/com/a4tech/product/newproducts/criteria/parser/NewProProductImprintmethodParser.java
- A4techExcelConvertionTool/main/java/supplier/91284NewPro/com/a4tech/product/newproducts/criteria/parser/NewProSizeParser.java
- A4techExcelConvertionTool/main/java/supplier/91284NewPro/com/a4tech/product/newproducts/mapping/NewProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/kuku/com/a4tech/product/kuku/mapping/KukuProductsExcelMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/service/postImpl/PostServiceImpl.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/ApplicationConstants.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
91284 Supplier completed & other code changes
> 91284 Supplier completed & other code changes

- A4techExcelConvertionTool/main/java/supplier/44620Apparel/com/a4tech/apparel/product/mapping/ApparelProductsExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/44620Apparel/com/a4tech/apparel/products/parser/ApparealProductAttributeParser.java
commit with description,imprint method and packaging.
> A4 data pro

- A4techExcelConvertionTool/main/java/supplier/42057Broberry/com/a4tech/product/broberry/mapping/BroberryExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/42057Broberry/com/a4tech/product/broberry/parser/BroberryProductAttributeParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/ApplicationConstants.java
Completed Options & Availability - Supplier 42057.
> Completed Options & Availability - Supplier 42057.

- A4techExcelConvertionTool/main/java/supplier/42057Broberry/com/a4tech/product/broberry/mapping/BroberryExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/42057Broberry/com/a4tech/product/broberry/parser/BroberryProductMaterialParser.java
- A4techExcelConvertionTool/main/java/supplier/42057Broberry/com/a4tech/product/broberry/parser/BroberrySkuParser.java
> commit with SKU and material(With the referce of mail)

- A4techExcelConvertionTool/pom.xml
- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/CutterBuckExcelMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/cutter/CutterBuckMaterialParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/cutter/CutterBuckSizeParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/cutter/cutter.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/controller/FileUpload.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelFactory.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
commit for rfgLine production and partial commit with CutterBuck
> commit for rfgLine production and partial commit for CutterBuck

- A4techExcelConvertionTool/main/java/supplier/42057Broberry/com/a4tech/product/broberry/mapping/BroberryExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/42057Broberry/com/a4tech/product/broberry/parser/BroberryProductAttributeParser.java
- A4techExcelConvertionTool/main/java/supplier/42057Broberry/com/a4tech/product/broberry/parser/BroberryProductMaterialParser.java
- A4techExcelConvertionTool/main/java/supplier/82588RiversEnd/com/a4tech/product/riversend/mapping/RiversEndExcelMapping.java
- A4techExcelConvertionTool/main/java/supplier/82588RiversEnd/com/a4tech/product/riversend/parser/RiverEndAttributeParser.java
- A4techExcelConvertionTool/main/java/supplier/82588RiversEnd/com/a4tech/product/riversend/parser/RiverEndPriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/CommonUtility.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
Revised requirement Code changes for 42057 & 82588.
> Revised requirement Code changes for 42057 & 82588

- A4techExcelConvertionTool/main/java/supplier/82588RiversEnd/com/a4tech/product/riversend/mapping/RiversEndExcelMapping.java
- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/HighCaliberLineExcelMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/highcaliberline/HighCalColorEntity.java
- A4techExcelConvertionTool/source/main/supplier/parser/highcaliberline/HighCaliberAttributeParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/highcaliberline/HighCaliberConstants.java
- A4techExcelConvertionTool/source/main/supplier/parser/highcaliberline/HighCaliberPriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelFactory.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
43442 HighCaliberLineUSA Commit
> 43442 HighCaliberLineUSA Commit

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/WholeSaleExcelMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/wholesale/WholeSaleAttributeParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/wholesale/WholeSalePriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelFactory.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/service/imple/MailServiceImpl.java
- A4techExcelConvertionTool/src/main/resources/sandbox-database.properties
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
> 91284_365Wholesale  Commit

- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
Change in application config file.
> Change in application config file.

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/CrystalDExcelMapping.java
- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/GoldstarCanadaExcelMapping.java
- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/MilestoneExcelMapping.java
- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/PSLMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/crystal/CrystalDPriceGridParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/crystal/CrystalDProductAttributeParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/milestone/MilestoneColorParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/milestone/MilestoneLookupData.java
- A4techExcelConvertionTool/source/main/supplier/parser/milestone/MilestonePriceGridParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/milestone/ProductAttributeParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/psl/PSLProductAttributeParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelFactory.java
done With Crystal D and Goldstar Canada
> Done With Crystal D and Goldstar Canada

- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelFactory.java
> Added milestone case

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/TomaxUsaMapping.java
> change in naming convention.

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/TomaxUsaMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/tomaxusa/TomaxProductTabParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/tomaxusa/TomaxSizeParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/tomaxusa/TomaxUsaAttributeParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/CommonUtility.java
Revised Changes For Tomax Supplier.
> Revised Changes For Tomax Supplier

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/PSLcadMapping.java
- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/TwintechMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/pslcad/PSLLookupColor.java
- A4techExcelConvertionTool/source/main/supplier/parser/pslcad/PSLcadProductAttributeParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/twintech/TwintechColorParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/twintech/TwintechLookupData.java
- A4techExcelConvertionTool/source/main/supplier/parser/twintech/TwintechPriceGridParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/twintech/TwintechProductAttributeParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelFactory.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
Done With Twintech supplier as per supplier changes.
> Done With Twintech supplier

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/BagMakersMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/BagMakers/BagMakerAttributeParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/BagMakers/BagMakerConstants.java
- A4techExcelConvertionTool/source/main/supplier/parser/BagMakers/BagMakersPriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelFactory.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
BagMaker Supplier-37940 Commit
> BagMaker Supplier-37940

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/BagMakersMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/BagMakers/BagMakersPriceGridParser.java
Bagmaker code change for imprint method upcharge.
> Bagmaker code change for imprint method upcharge.

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/BagMakersMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/BagMakers/BagMakersPriceGridParser.java
> BagMaker Code Changes

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/BagMakersMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/BagMakers/BagMakerAttributeParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/BagMakers/BagMakersPriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/lookup/model/Colors.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/lookup/service/LookupServiceData.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/lookup/service/restService/LookupRestService.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/product/model/Product.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/CommonUtility.java
- A4techExcelConvertionTool/src/main/resources/sandbox-externalApiEndPoints.properties
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
37940 Bag Makers Inc , MSSQL DB code
> 37940 Bag Makers Inc , MSSQL DB code

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/SunGraphixMapping.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/util/CommonUtility.java
> Sungraphix code changes

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/SolidDimensionMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/solidDimension/SolidDimensionPriceGridParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/solidDimension/SolidDimesionAttributeParser.java
Solid Dimesion New File Commit
> Solid Dimesion New File Commit

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/SunGraphixRevisedMapping.java
> SunGraphix Upcharge Change

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/SportUSAMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/SportsAzxUsa/SportsUsaApplicationConstatnt.java
- A4techExcelConvertionTool/source/main/supplier/parser/SportsAzxUsa/SportsUsaAttributeParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/SportsAzxUsa/SportsUsaColorParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/SportsAzxUsa/SportsUsaPriceGridParser.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelFactory.java
- A4techExcelConvertionTool/src/main/resources/sandbox-database.properties
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
> 30250 AZX Sport USA Commit.

- A4techExcelConvertionTool/source/main/supplier/com/a4tech/supplier/mapper/SportAzxCandMapping.java
- A4techExcelConvertionTool/source/main/supplier/parser/SportAzxCanada/SportsAzxCanColorParser.java
- A4techExcelConvertionTool/source/main/supplier/parser/SportAzxCanada/SportsCanadaApplicationConstatnt.java
- A4techExcelConvertionTool/src/main/java/com/a4tech/core/excelMapping/ExcelFactory.java
- A4techExcelConvertionTool/src/main/resources/spring/application-config.xml
30251 AZXSportCanada   Supplier.
> 30251 AZXSportCanada   Supplier.
